# MYSQL
db.mysql.url=jdbc:mysql://localhost:3306/escalada
db.mysql.user=admin
db.mysql.password=1234

# POSTGRES
db.postgres.url=jdbc:postgresql://localhost:5432/escalada
db.postgres.user=admin
db.postgres.password=1234